### ISSUE TITLE
Shown keybinds are not consistant with different keyboard layouts

### ISSUE THREAD

**Issue by PainDesu** [MrakDun-desu/BlockStacker-desu#15]
I use czech layout, so the 3 buttons next to m are "," "." and "-". If I try to bind "-" it shows up as "/" in game (I am guessing that's from ENG layout).

Expected:
![image](https://user-images.githubusercontent.com/43996537/204635219-285e1095-5469-4a1e-8379-395c89757479.png)

Reality:
![image](https://user-images.githubusercontent.com/43996537/204635304-ba6e1c61-fec2-4482-a027-276a12024da3.png)

The binds ingame work fine but it is confusing.

**Comment by MrakDun-desu** [comment]
I understand the issue, but it's not possible to be fixed by me. The Unity Input System detects the keys independent of the keyboard layout that you're using, so it needs to display them like this as well.

The control is mapped to a particular key on a keyboard, *not* to a particular character that pressing that key would produce. Display names are just set to the english US by default. Fixing it would require rewriting the whole Input System from scratch.
